a=int(input("enter first number"))
b=int(input("enter second number"))
print("\arithmetic operations results:")
print(f"addition:{a}{b}={a+b}")
print(f"subtraction:{a}-{b}={a-b}")
print(f"multiplication:{a}*{b}={a*b}")
print(f"division:{a}{b}={a/b}")
print(f"modulas:{a}%{b}={a%b}")
print(f"floor division:{a}//{b}={a//b}")
print(f"exponentiation:{a}**{b}={a**b}")
